[package]
name = "Licence_Generator"
version = "0.1.0"
edition = "2021"

[dependencies]
libsodium-sys = "0.2.6"
clap = { version = "4.5.7", features = ["derive"] }
base64 = "0.21.7"

[[bin]]
name = "sign"
path = "src/sign.rs"

[[bin]]
name = "verify"
path = "src/verify.rs"